### ISSUE TITLE
multiple materials on the same mesh

### ISSUE THREAD

**Issue by delepoulle** [stig-atle/io_scene_pbrt#10]
When I assign multiple materials to one mesh (to different parts of the mesh), only the first one seem to be affect to the whole mesh. I wonder if it's a problem of the exporter or of PBRT itself and if there is a way to do this.

**Comment by stig-atle** [comment]
Multiple materials are a missing feature in the exporter.
Currently it uses the internal ply exporter in blender, exporting each object to ply file.
I need to do some work to support multiple materials (Split the mesh based on faces with each material).

Thank you for reporting it, I will get back to it soon, it's a important to support this feature.

**Comment by stig-atle** [comment]
I'm working on this now. I'm removing the .ply format, then I write out the shapes in pbrt's triangle mesh format, I have vertex pos, face index, and normals fixed, now I need to rewrite the export of uv's, this has changed a lot since last time, so this is the hardest part to fix. 
Once the uv's are fixed I will split the triangle meshes based on material assigned, so that you can have multiple materials per triangle mesh.

**Comment by stig-atle** [comment]
Sorry that it took so long, working on this now. I'm almost done. I just have the update the viewport preview code to make it work properly, I expect to have it done within a couple of days.
Here is a test render I did today with this, green glass and one face with matte white.

![image](https://user-images.githubusercontent.com/7627610/73199411-1931fd00-4135-11ea-98be-c51ceb4de062.png)
![image](https://user-images.githubusercontent.com/7627610/73199466-2ea72700-4135-11ea-8c7a-b02806dcb44e.png)

**Comment by delepoulle** [comment]
Nice ! I will test this as soon you will comit it.

**Comment by stig-atle** [comment]
Code has been pushed. I also added a simple sample scene to test with.
Let me know if you run into some issues, reopen the issue if something goes wrong. I'll close it for now and move on to the next thing to fix.

**Comment by delepoulle** [comment]
Very cool ! The multi-material works fine for me !
![Capture d’écran_2020-01-31_10-46-12](https://user-images.githubusercontent.com/15376925/73529807-9ac8aa00-4417-11ea-852f-8eb65226aebc.png)

**Comment by stig-atle** [comment]
Great! Thank you for the reply, glad it worked!
