### ISSUE TITLE
issue with subsurface modifier

### ISSUE THREAD

**Issue by delepoulle** [stig-atle/io_scene_pbrt#24]
When a modifier is used, the mesh is not exported correctly unless the modifier is apply and the mesh turn in edit mode.

I use blender 2.82. The exporter work but if I use the subsurface modifier :
- if I don't apply it, the exporter dont use it (why not ?)
- if I apply it, many part of the mesh are not exported ! I read the pbrt file produced and the number of vertex is not changed !
- if I turn into edit mode, the mesh is now exported correctly

I think there is the same problem with many (all ?) modifier. A very cool solution would to have a checkbox like "apply modifier before export" in order to keep the modifiers in the blend file.

**Comment by stig-atle** [comment]
Hi, thank you for reporting the issue,
it's the way I'm accessing the mesh that causes it. I have seen this problem before.
I will prioritize this fix now and get it sorted. It's not good that it exports the way it does now, it needs to be fixed.

**Comment by stig-atle** [comment]
I have pushed some fixes for this now. Please give the latest version a test and reply back.

**Comment by delepoulle** [comment]
I've just test it and it's great ! The modifiers are now exported into the pbrt scene.
Thanks a lot, I will appreaciate to use this fantastic plugin.
As I think the problem is solved, I close the thread.
